language: node_js
node_js:
  - 14
branches:
  only:
    - main # Set the branch you want to trigger CI/CD for

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@latest

install:
  - npm install

script:
  - npm run build